// <auto-generated />
namespace WindowsEmpleados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CrearBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CrearBase));
        
        string IMigrationMetadata.Id
        {
            get { return "202211140214385_CrearBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
